#!/usr/bin/env python3
"""Split the combined NetCDF climatology files into separate datasets.

This script splits NetCDF files generated by combine_netcdf_files.py
into separate datasets to optimize coverage size. Files will be split by
time period (historical vs projected) and by landcover (static vs dynamic).

Historical files will only have historical era (1976-2005) and the historical scenario. 
The Maurer baseline will be included in historical files.

Projected files will only have projected eras (2016_2045, 2046_2075, 2071_2100) and 
projected scenarios (rcp26, rcp45, rcp60, rcp85).

This script will produce the following files:

- combined_static_historical.nc (all models, historical era, historical scenario, static landcover)
- combined_dynamic_historical.nc (all models, historical era, historical scenario, dynamic landcover)
- combined_static_projected.nc (all models, projected eras, projected scenarios, static landcover)
- combined_dynamic_projected.nc (all models, projected eras, projected scenarios, dynamic landcover)

Example usage:
	python split_combined_netcdf_file.py <input_file> <output_dir>
"""

import os
import argparse
import xarray as xr

def main(input_file, output_dir):
	ds = xr.open_dataset(input_file)

	# Dimension values
	era_vals = ds['era'].values
	scenario_vals = ds['scenario'].values
	landcover_vals = ds['landcover'].values

	# Indices for splits
	era_hist_idx = [i for i, v in enumerate(era_vals) if v == 0]  # 1976-2005
	era_proj_idx = [i for i, v in enumerate(era_vals) if v in [1,2,3]]  # projected eras
	scenario_hist_idx = [i for i, v in enumerate(scenario_vals) if v == 0]  # historical
	scenario_proj_idx = [i for i, v in enumerate(scenario_vals) if v in [1,2,3,4]]  # projected scenarios
	landcover_static_idx = [i for i, v in enumerate(landcover_vals) if v == 1]  # static
	landcover_dynamic_idx = [i for i, v in enumerate(landcover_vals) if v == 0]  # dynamic

	# Output file names
	outfiles = {
		'combined_static_historical.nc': dict(era=era_hist_idx, scenario=scenario_hist_idx, landcover=landcover_static_idx),
		'combined_dynamic_historical.nc': dict(era=era_hist_idx, scenario=scenario_hist_idx, landcover=landcover_dynamic_idx),
		'combined_static_projected.nc': dict(era=era_proj_idx, scenario=scenario_proj_idx, landcover=landcover_static_idx),
		'combined_dynamic_projected.nc': dict(era=era_proj_idx, scenario=scenario_proj_idx, landcover=landcover_dynamic_idx),
	}

	os.makedirs(output_dir, exist_ok=True)

	for fname, idxs in outfiles.items():
		subset = ds.isel(
			era=idxs['era'],
			scenario=idxs['scenario'],
			landcover=idxs['landcover']
		)
		out_path = os.path.join(output_dir, fname)
		subset.to_netcdf(out_path)
		print(f"Wrote {out_path}")

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description="Split combined NetCDF into 4 files by era/scenario/landcover.")
	parser.add_argument("input_file", help="Path to combined NetCDF file")
	parser.add_argument("output_dir", help="Directory to write output NetCDF files")
	args = parser.parse_args()
	main(args.input_file, args.output_dir)
