#!/usr/bin/env python3
"""
Submit SLURM job scripts generated by generate_slurm_jobs.py.

Simple script that finds all .sh files in a directory and submits them as SLURM batch jobs.
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Submit SLURM job scripts for streamflow processing",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument(
        "scripts_dir",
        type=str,
        help="Directory containing SLURM job scripts (.sh files)"
    )
    
    return parser.parse_args()


def submit_job(script_path):
    """Submit a single SLURM job script."""
    try:
        result = subprocess.run(
            ["sbatch", str(script_path)],
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode == 0:
            # Extract job ID from output (typically "Submitted batch job 12345")
            job_id = result.stdout.strip().split()[-1]
            print(f"Submitted: {script_path.name} (Job ID: {job_id})")
            return True, job_id
        else:
            print(f"Failed to submit {script_path.name}: {result.stderr}", file=sys.stderr)
            return False, None
            
    except subprocess.TimeoutExpired:
        print(f"Timeout submitting {script_path.name}", file=sys.stderr)
        return False, None
    except FileNotFoundError:
        print("Error: sbatch command not found", file=sys.stderr)
        return False, None


def main():
    """Main function to submit SLURM jobs."""
    args = parse_arguments()
    
    # Convert to Path object
    scripts_dir = Path(args.scripts_dir)
    
    # Validate scripts directory
    if not scripts_dir.exists():
        print(f"Error: Scripts directory does not exist: {scripts_dir}", file=sys.stderr)
        sys.exit(1)
    
    # Find script files
    script_files = list(scripts_dir.glob("*.sh"))
    
    # Filter out non-executable files and sort
    executable_scripts = []
    for script in script_files:
        if script.is_file() and os.access(script, os.X_OK):
            executable_scripts.append(script)
        else:
            print(f"Warning: Skipping non-executable file: {script}")
    
    script_files = sorted(executable_scripts)
    
    if not script_files:
        print(f"No executable .sh files found in {scripts_dir}")
        sys.exit(1)
    
    print(f"Found {len(script_files)} script files to submit")
    
    # Track submission results
    successful_submissions = []
    failed_submissions = []
    
    # Submit jobs
    for i, script_path in enumerate(script_files, 1):
        print(f"[{i}/{len(script_files)}] ", end="")
        
        # Submit the job
        success, job_id = submit_job(script_path)
        
        if success:
            successful_submissions.append((script_path, job_id))
        else:
            failed_submissions.append(script_path)
    
    # Print summary
    print(f"\nSUMMARY:")
    print(f"Successful submissions: {len(successful_submissions)}")
    print(f"Failed submissions: {len(failed_submissions)}")
    
    if failed_submissions:
        print(f"\nFailed submissions:")
        for script_path in failed_submissions:
            print(f"  {script_path.name}")
    
    # Write submission log
    log_file = scripts_dir / "submission_log.txt"
    with open(log_file, 'w') as f:
        f.write(f"SLURM Job Submission Log\n")
        f.write(f"========================\n")
        f.write(f"Submission time: {os.popen('date').read().strip()}\n")
        f.write(f"Scripts directory: {scripts_dir}\n")
        f.write(f"Successful submissions: {len(successful_submissions)}\n")
        f.write(f"Failed submissions: {len(failed_submissions)}\n\n")
        
        if successful_submissions:
            f.write("Successfully submitted:\n")
            for script_path, job_id in successful_submissions:
                f.write(f"  {script_path.name}: {job_id}\n")
            f.write("\n")
        
        if failed_submissions:
            f.write("Failed submissions:\n")
            for script_path in failed_submissions:
                f.write(f"  {script_path.name}\n")
    
    print(f"Submission log written to: {log_file}")
    
    if successful_submissions:
        username = os.environ.get('USER', os.environ.get('LOGNAME', 'your_username'))
        print(f"To monitor job status: squeue -u {username}")
    
    # Exit with appropriate code
    if failed_submissions:
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()